### ISSUE TITLE
[Bug] dev environment is ignored for admin and blog-front default scripts

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/cli-service-pm2#6]
run the application with `npm run dev`, the admin-panel and the blog-front are running with the prod script instead of the dev script.
can be overridden manually through greenpress config file, but expected to work by default.

**Comment by davidmeirlevy** [comment]
@drorrose your PR has approved.
You can merge and close this issue.

**Comment by drorrose** [comment]
Fixed on commit fd0d991
